### ISSUE TITLE
在goroutine中执行unmarshal报 `invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by Danceiny** [liamylian/jsontime#1]
在goroutine中执行似乎会报 `invalid memory address or nil pointer dereference`（换成标准库则无报错），错误详情如下：

```
2018/11/20 23:20:25 msg: {"body": "W1tdLCB7InkiOiAyODc4LCAieCI6IDU0NTZ9LCB7ImNob3JkIjogbnVsbCwgImNhbGxiYWNrcyI6IG51bGwsICJlcnJiYWNrcyI6IG51bGwsICJjaGFpbiI6IG51bGx9XQ==", "headers": {"origin": "gen25086@huangzhen-PC", "root_id": "749d3493-b099-4046-af97-1058c6a5ee15", "expires": null, "shadow": null, "id": "749d3493-b099-4046-af97-1058c6a5ee15", "kwargsrepr": "{'y': 2878, 'x': 5456}", "lang": "py", "retries": 0, "task": "worker.add_reflect", "group": null, "timelimit": [null, null], "parent_id": null, "argsrepr": "()", "eta": null}, "content-type": "application/json", "properties": {"priority": 0, "body_encoding": "base64", "correlation_id": "749d3493-b099-4046-af97-1058c6a5ee15", "reply_to": "bf935db4-3c52-3084-8cd3-72d99d0d139e", "delivery_info": {"routing_key": "celery", "exchange": ""}, "delivery_mode": 2, "delivery_tag": "2a396d59-9841-4eac-a6d7-dfb1a0b73b93"}, "content-encoding": "utf-8"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x628b22]

goroutine 38 [running]:
github.com/Danceiny/go%2efastjson.(*CustomTimeExtension).UpdateStructDescriptor.func2(0xc42016c090, 0xc420110280)
	/home/huangzhen/go/src/github.com/Danceiny/go.fastjson/json.go:136 +0x112
github.com/Danceiny/go%2efastjson.(*funcDecoder).Decode(0xc4200c6308, 0xc42016c090, 0xc420110280)
	/home/huangzhen/go/src/github.com/Danceiny/go.fastjson/json.go:148 +0x3d
github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc4200daf00, 0xc42016c010, 0xc420110280)
	/home/huangzhen/go/src/github.com/json-iterator/go/reflect_struct_decoder.go:1010 +0x86
github.com/json-iterator/go.(*generalStructDecoder).decodeOneField(0xc4200dafe0, 0xc42016c010, 0xc420110280)
	/home/huangzhen/go/src/github.com/json-iterator/go/reflect_struct_decoder.go:548 +0x116
github.com/json-iterator/go.(*generalStructDecoder).Decode(0xc4200dafe0, 0xc42016c010, 0xc420110280)
	/home/huangzhen/go/src/github.com/json-iterator/go/reflect_struct_decoder.go:505 +0x74
github.com/json-iterator/go.(*structFieldDecoder).Decode(0xc4200dbaa0, 0xc42016c000, 0xc420110280)
	/home/huangzhen/go/src/github.com/json-iterator/go/reflect_struct_decoder.go:1010 +0x86
github.com/json-iterator/go.(*fiveFieldsStructDecoder).Decode(0xc42010c360, 0xc42016c000, 0xc420110280)
	/home/huangzhen/go/src/github.com/json-iterator/go/reflect_struct_decoder.go:720 +0xc5
github.com/json-iterator/go.(*Iterator).ReadVal(0xc420110280, 0x69de20, 0xc42016c000)
	/home/huangzhen/go/src/github.com/json-iterator/go/reflect.go:78 +0x82
github.com/json-iterator/go.(*frozenConfig).Unmarshal(0xc4200e01e0, 0xc42016a000, 0x371, 0x371, 0x69de20, 0xc42016c000, 0x0, 0x0)
	/home/huangzhen/go/src/github.com/json-iterator/go/config.go:348 +0xb0
```

**Comment by liamylian** [comment]
确定原因为time.Time类型的字段，如果unmarshal时为空字符串会panic。感谢fix
